spring:
  application:
    name: microservice-consumer-movie-ribbon-withput-eureka
server:
  port: 8011
eureka:
  client:
    healthcheck:
    #  enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
   enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
