spring:
  application:
    name: microservice-consumer-movie-feign
server:
  port: 7911
#user:
 # userServicePath: http://localhost:7900/simple/
eureka:
  client:
    instance:
       prefer-ip-address: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password555@localhost:8761/eureka

 