spring:
  application:
    name: microservice-consumer-movie-feign
server:
  port: 7911
eureka:
  client:
    healthcheck:
  #   enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    emabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000

