spring:
  application:
    name: microservice-consumer-movie-feign
server:
  port: 7911
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password555@localhost:8761/eureka
  instance:
    prefer-ip-address: true