server:
  port: 7911
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    #platform: h2
    #schema: classpath:schema.sql,
    #data: classpath:data.sql
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shoppingmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservice-provider-users
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
eureka:
  client: 
    serviceUrl:
      defaultZone: http://user:password555@localhost:8761/eureka
 
# instance:
  # prefer-ip-address: true
  #  instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    